-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 15:01:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema alpaka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alpaka` DEFAULT CHARACTER SET utf8 ;
USE `alpaka` ;

-- -----------------------------------------------------
-- Table `alpaka`.`users`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  `birth_date` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `state` VARCHAR(15) NOT NULL,
  `close_date` DATE NULL,
  `updated_at` VARCHAR(45) NULL,
  `created_at` DATE NOT NULL,
  `remember_token` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`countries`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL COMMENT 'eg Suisse,France, Italie...',
  `acronym` VARCHAR(5) NOT NULL COMMENT 'eg CH, IT, FR..',
  `country_code` INT NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`npas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpaka`.`npas` (
  `npa_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(55) NOT NULL,
  `code` INT NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  PRIMARY KEY (`npa_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`payments`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `mode` VARCHAR(45) NOT NULL COMMENT 'eg MasterCard, Visa...',
  `num_card` VARCHAR(60) NULL DEFAULT NULL,
  `exp_date` DATE NULL DEFAULT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  INDEX (`user_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `C1`
    FOREIGN KEY (`user_id`)
    REFERENCES `alpaka`.`users` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`wineries`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`wineries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `website` VARCHAR(255) NULL DEFAULT NULL,
  `slug` VARCHAR(45) NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  INDEX (`country_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `C2`
    FOREIGN KEY (`country_id`)
    REFERENCES `alpaka`.`countries` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`categories`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`wines`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`wines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `winery_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `price_wine` FLOAT NOT NULL,
  `origin` VARCHAR(45) NOT NULL COMMENT 'eg Vaud, Valais..',
  `size` VARCHAR(45) NOT NULL COMMENT 'eg 75cl, 50cl..',
  `varietal` VARCHAR(45) NOT NULL COMMENT 'eg aglianico, Barbera, Bobal',
  `good_year` TINYINT(1) NOT NULL,
  `date_production` DATE NOT NULL,
  `serv_temp` INT NOT NULL,
  `description` LONGTEXT NOT NULL,
  `stock_status` TINYINT(1) NOT NULL,
  `conditioning` VARCHAR(45) NOT NULL COMMENT '1,carton de 6,carton de 12...',
  `ranking` INT NULL,
  `alcohol_level` FLOAT NOT NULL,
  `image` VARCHAR(60) NULL,
  `slug` VARCHAR(45) NOT NULL,
  `delivery_delay` VARCHAR(10) NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX (`winery_id` ASC),
  INDEX (`country_id` ASC),
  INDEX `fk_wine_category1_idx` (`category_id` ASC),
  CONSTRAINT `C3`
    FOREIGN KEY (`winery_id`)
    REFERENCES `alpaka`.`wineries` (`id`),
  CONSTRAINT `C4`
    FOREIGN KEY (`country_id`)
    REFERENCES `alpaka`.`countries` (`id`),
  CONSTRAINT `fk_wine_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `alpaka`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`promotions`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`promotions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wine_id` INT NULL,
  `discount` INT NOT NULL,
  `pourcentage` TINYINT(1) NOT NULL,
  `date_start` DATE NOT NULL,
  `date_end` DATE NOT NULL,
  `code` VARCHAR(10) NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_promotion_wine1_idx` (`wine_id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  CONSTRAINT `fk_promotion_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `alpaka`.`wines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`ratings`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wine_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `comment` LONGTEXT NULL DEFAULT NULL,
  `rate` INT NOT NULL COMMENT '1,2,3,4,5',
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX (`wine_id` ASC),
  INDEX (`user_id` ASC),
  CONSTRAINT `C5`
    FOREIGN KEY (`wine_id`)
    REFERENCES `alpaka`.`wines` (`id`),
  CONSTRAINT `C6`
    FOREIGN KEY (`user_id`)
    REFERENCES `alpaka`.`users` (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `alpaka`.`foods`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`foods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`wines_with_foods`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`wines_with_foods` (
  `wine_id` INT NOT NULL,
  `food_id` INT NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  INDEX (`wine_id` ASC),
  INDEX (`food_id` ASC),
  CONSTRAINT `C7`
    FOREIGN KEY (`wine_id`)
    REFERENCES `alpaka`.`wines` (`id`),
  CONSTRAINT `C8`
    FOREIGN KEY (`food_id`)
    REFERENCES `alpaka`.`foods` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`posts`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(25) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `cover` VARCHAR(60) NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`user_id` ASC),
  CONSTRAINT `C9`
    FOREIGN KEY (`user_id`)
    REFERENCES `alpaka`.`users` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`comments`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `message` LONGTEXT NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`user_id` ASC),
  INDEX (`post_id` ASC),
  CONSTRAINT `C10`
    FOREIGN KEY (`user_id`)
    REFERENCES `alpaka`.`users` (`id`),
  CONSTRAINT `C11`
    FOREIGN KEY (`post_id`)
    REFERENCES `alpaka`.`posts` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`carts_items`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`carts_items` (
  `wine_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  INDEX `fk_wine_has_user_user1_idx` (`user_id` ASC) ,
  INDEX `fk_wine_has_user_wine1_idx` (`wine_id` ASC) ,
  CONSTRAINT `fk_wine_has_user_wine1`
    FOREIGN KEY (`wine_id`)
    REFERENCES `alpaka`.`wines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wine_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `alpaka`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`addresses`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `npa_id` INT NOT NULL,
  `title` VARCHAR(15) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `addressLine` VARCHAR(55) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX (`user_id` ASC),
  INDEX (`country_id` ASC),
  INDEX (`npa_id` ASC),
  CONSTRAINT `C12`
    FOREIGN KEY (`user_id`)
    REFERENCES `alpaka`.`users` (`id`),
  CONSTRAINT `C13`
    FOREIGN KEY (`country_id`)
    REFERENCES `alpaka`.`countries` (`id`),
  CONSTRAINT `C14`
    FOREIGN KEY (`npa_id`)
    REFERENCES `alpaka`.`npas` (`npa_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`orders`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'bill',
  `user_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  `promotion_id` INT NULL,
  `shipped_date` DATE NOT NULL,
  `value_discount` INT NULL,
  `total_price` FLOAT NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NOT NULL COMMENT 'When order created',
  INDEX (`user_id` ASC),
  INDEX (`payment_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_order_promotion1_idx` (`promotion_id` ASC),
  CONSTRAINT `C15`
    FOREIGN KEY (`user_id`)
    REFERENCES `alpaka`.`addresses` (`user_id`),
  CONSTRAINT `C16`
    FOREIGN KEY (`payment_id`)
    REFERENCES `alpaka`.`payments` (`user_id`),
  CONSTRAINT `fk_order_promotion1`
    FOREIGN KEY (`promotion_id`)
    REFERENCES `alpaka`.`promotions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alpaka`.`orders_items`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `alpaka`.`orders_items` (
  `order_id` INT NOT NULL,
  `wine_id` INT NOT NULL,
  `promotion_id` INT NULL,
  `quantity` INT NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `value_discount` INT NULL,
  `order_item_price` FLOAT NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NULL,
  INDEX (`order_id` ASC),
  INDEX (`wine_id` ASC),
  INDEX `fk_order_item_promotion1_idx` (`promotion_id` ASC),
  CONSTRAINT `C17`
    FOREIGN KEY (`order_id`)
    REFERENCES `alpaka`.`orders` (`id`),
  CONSTRAINT `C18`
    FOREIGN KEY (`wine_id`)
    REFERENCES `alpaka`.`wines` (`id`),
  CONSTRAINT `fk_order_item_promotion1`
    FOREIGN KEY (`promotion_id`)
    REFERENCES `alpaka`.`promotions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;